version: "3.9"

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=mysql+pymysql://root:Koraliny2406%40@db:3306/facialrecognition
    restart: on-failure

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: facialrecognition
      MYSQL_ROOT_PASSWORD: Koraliny2406@
    volumes:
      - mysqldata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pKoraliny2406@"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysqldata:
