"""Add ON DELETE CASCADE to user_id in user_logs

Revision ID: 0ace93f7ca85
Revises: d68cadfc9fc6
Create Date: 2025-07-22 17:47:54.600750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ace93f7ca85'
down_revision: Union[str, Sequence[str], None] = 'd68cadfc9fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('user_logs_ibfk_1'), 'user_logs', type_='foreignkey')
    op.create_foreign_key(None, 'user_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_logs', type_='foreignkey')
    op.create_foreign_key(op.f('user_logs_ibfk_1'), 'user_logs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
