"""Changing passive deletes to all to correct problems

Revision ID: 7dc6d2bd8683
Revises: 0ace93f7ca85
Create Date: 2025-07-22 18:12:26.183455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dc6d2bd8683'
down_revision: Union[str, Sequence[str], None] = '0ace93f7ca85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
