"""Fixing other relationship errors

Revision ID: d68cadfc9fc6
Revises: a591f5590e8c
Create Date: 2025-07-21 18:49:31.190918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd68cadfc9fc6'
down_revision: Union[str, Sequence[str], None] = 'a591f5590e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_logs', 'user_name')
    op.drop_column('user_logs', 'user_image_path')
    op.drop_column('user_logs', 'user_position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_logs', sa.Column('user_position', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user_logs', sa.Column('user_image_path', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('user_logs', sa.Column('user_name', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
